name: Run Lune

on:
    workflow_dispatch:

jobs:
    run-lune:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get latest Lune release
              id: lune-release
              run: |
                  curl -s https://api.github.com/repos/lune-org/lune/releases/latest \
                    | grep "browser_download_url" \
                    | grep "linux" \
                    | cut -d '"' -f 4 \
                    | wget -qi -

            - name: Extract Lune binary
              run: |
                  tar -xf lune-*-x86_64-unknown-linux-gnu.tar.gz
                  chmod +x lune
                  sudo mv lune /usr/local/bin/

            - name: Run Lune script
              run: |
                  echo 'print("Hello from Lune!")' > hello.luau
                  lune hello.luau
