name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  release-client:
    defaults:
      run:
        working-directory: client

    runs-on: windows-latest

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ github.token }}

      - name: Install tools
        run: aftman install --no-trust-check

      - name: Build & Compile
        run: |
          pnpm run action-pnpm-build --verbose

      - name: Bundle Luau
        run: pnpm run action-pnpm-bundle

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            client/dist/**/*
          token: ${{ secrets.GITHUB_TOKEN }}
          append_body: true
          generate_release_notes: true

  release-server:
    defaults:
      run:
        working-directory: ./server

    runs-on: windows-latest

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Cargo Project
        run: cargo build --release

      - name: Upload Cargo Release Assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "**/roblox-chess-script.exe"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
